### ISSUE TITLE
Bootloadr address

### ISSUE THREAD

**Issue by pebri86** [atc1441/DaFlasherFiles#1]
Hi, great work.
I want to update bootloader and SD version to 6.0, but how to change address to 0x78000?

**Comment by atc1441** [comment]
Hi, the bootloader address is allready at 0x78000

changeing it does work but needs aditional bootloader todo so

**Comment by pebri86** [comment]
So is it possible to flash wasp-bootloader with daflasher?

**Comment by atc1441** [comment]
When it is made compatible so pinout changed and on 0x78000 it should be no problem.

But please try it on an open watch first to see if its working so you can restore it

**Comment by pebri86** [comment]
Thanks, 

I managed to port wasp bootloader to p8 and it's working perfectly without needed opening the case. 
Micropython and wasp-os also working on the p8 but it's missing touchscreen.

**Comment by atc1441** [comment]
Nice to hear it worked well :)
