### ISSUE TITLE
Is there an alternative to the da fit app?

### ISSUE THREAD

**Issue by copypasteearth** [atc1441/DaFlasherFiles#13]
Hi, I don't know that much about these watches but I had an old watch before and the app was on GitHub so I could clone it and customize it. I was wondering if I could do the same with da fit. I just ordered a LIGE smartwatch and I read all of the reviews on dafit app and it's not looking good.

**Comment by atc1441** [comment]
Hey. 
This project is more about replacing all stock firmware and App.

So you could use GadgetBridge if you want there you can customize everything but it is less fitness orientated.

Or the D6Notification app but that one only works with the custom firmware ATCwatch

**Comment by ildar** [comment]
Yes, please move here:
https://codeberg.org/Freeyourgadget/Gadgetbridge/issues/1898

**Comment by copypasteearth** [comment]
@ildar can gadgetbridge brick your watch?
I have LIGE watch, it pairs as I9M

**Comment by ildar** [comment]
No
It's offtopic here
