### ISSUE TITLE
Pairing rejected by ATCwatch

### ISSUE THREAD

**Issue by kmhaeren** [atc1441/DaFlasherFiles#14]
Hi Aaron
First and foremost; awesome job, bought this watch just to try out your daflasher app,
and it works great! Only problem is, I can't connect to the watch after flashing;

The ATCwatch appears in my phone's list of bluetooth devices, 
but when clicking it; a pop-up appears saying "Pairing rejected by ATCwatch",

Is there anything I should do to allow the watch to pair with the phone?

**Comment by atc1441** [comment]
Hey. No need to pair it, on BLE it works differently

You can use D6Notification to connect to it directly

**Comment by kmhaeren** [comment]
Hadn't found that gem before, this is truly incredible
