### ISSUE TITLE
daflasher won't flash second bootloader

### ISSUE THREAD

**Issue by 0x416c6578** [atc1441/DaFlasherFiles#2]
i have been having problems with flashing the second bootloader to my watch. the first one flashed fine, however whenever i try to flash the second bootloader, the app gives the error: "Error BLUETOOTH ADAPTER DISABLED". i have tried with a nexus 7 2013 (8.1.0), and nexus 5x (8.1.0), with both devices showing the same error. i have tried restarting the devices, restarting the app, toggling bluetooth, none of which have worked. 
i did have a partial success when i enabled bluetooth in quick settings quickly after selecting the file to flash. this would sort of start flashing, but it would be stuck at 0% and eventually fail, giving the error "Error GATT ERROR". (i think this is just the app being fooled into thinking it is connected to the watch when it isn't).
edit: to clarify, this is with the p8

**Comment by 0x416c6578** [comment]
quick fix: use the nRF connect app to flash the files works fine, even if it slower

**Comment by atc1441** [comment]
An update of the DaFlasher will be uploaded these days that fixes the issue,

Reason for it was that the delay after turning Bluetooth on in the dfu process is to short for some devices that takes some time to enable it again.

**Comment by atc1441** [comment]
New update is now online
