### ISSUE TITLE
Flash Bootloader using ST-Link

### ISSUE THREAD

**Issue by pebri86** [atc1441/DaFlasherFiles#3]
Hi, which files should i use if i want to flash bootloader using st-link?
I flash my p8 with wasp-bootloader and cannot back to your dafitbootloader using DFU package (error DATA_SIZE_LIMIT). I think wasp-bootloader using s132 softdevice which is too big.

Thanks

**Comment by atc1441** [comment]
Hi. If you are on windows just use the D6Arduino.rar and restore the P8 to stock in it. That will flash the bootloader via the st-link

**Comment by pebri86** [comment]
Hi, OK that was solve my problem

Thank You very much, this project really progressing.
