### ISSUE TITLE
Watch P8b is not detected

### ISSUE THREAD

**Issue by Steakache** [atc1441/DaFlasherFiles#5]
I recently acquired a p8 watch.
The watch is detected with the dafit app but not with DaFlasher.
This is the info in "About" :
_P8b
MOY-TIN5-1.7.8_

**Comment by atc1441** [comment]
Hi. Sounds to me like its still connected in the DaFit app.
You need to remove it there first.

**Comment by Steakache** [comment]
Wow, fast after sales service :). Thanks for the quick reply.
I tried but it doesn't seem to change anything.

**Comment by Steakache** [comment]
I reboot the watch and the phone. And, it's work now. 👍 
Sorry for the inconvenience

**Comment by atc1441** [comment]
No problem :) 

Please also try to press the scan button in DaFlasher.
It does need access/permission to location to be able to search for ble devices.

Please also try to search for the P8 with the app nRFconnect and see if it finds it

**Comment by atc1441** [comment]
Perfect :) 

Also be aware that that TIN5 version most likely has a new accl so step counting is not working right now. 

You can join our discord server for more infos
https://discord.com/invite/TRktBnv

**Comment by stefan123t** [comment]
Found the latest firmware image on the [upgrade factory](http://api2.crrepa.com/upgrade/factory/?mac=12:34:56:78:9A:BC&version=MOY-TIN5-1.7.8):

```
$ curl http://api2.crrepa.com/upgrade/factory?mac\=12:34:56:78:9A:BC\&version\=MOY-TIN5-1.7.8 | jq .
{
  "code": 0,
  "mcu": 3,
  "message": "发现新版本",
  "type": 0,
  "version": "MOY-TIN5-1.8.2",
  "path": "http://api2.crrepa.com/uploads/files/d4d40514824af964d472515a15a84fc6.bin",
  "url": "http://api2.crrepa.com/uploads/files/d4d40514824af964d472515a15a84fc6.bin",
  "md5": "f5cd02e23ee927ce8b6e6a9240b8db5c",
  "log": "软件优化",
  "log_en": "software optimization",
  "size": 166460
}
```
